### PR TITLE
Changed config and registry to app module. Simplified traversal API

### PR DESCRIPTION
**Pull request by davebshow**

### CODE REVIEW

**Comment by leifurhauks** [comment]
LGTM!

**Comment by leifurhauks** [comment]
For traversals like `session.traversal(MyVertex).has(MyVertex.__mapping__.my_prop, ('binding', 'value'))`, is there any way for the property key to be retrieved from the property descriptor, so we could have something like `session.traversal(MyVertex).has(MyVertex.my_prop, ('binding', 'value'))`?

**Comment by davebshow** [comment]
Well, yes, actually, that is a great idea. In the absence of an instantiated obj, I think we could return the mapping...let's see.

**Comment by davebshow** [comment]
59dc329c1e8346c00470fae3ab6a3e1c10e61312 implements your suggestion

**Comment by davebshow** [comment]
I'm going to merge this and setup pytest before working on anything new.

**Pull request merged**
