### PR TITLE
write initial concrete impls for Float, Bool

### PR DESCRIPTION
**Pull request by leifurhauks**
`Float` and `Bool` couldn't be instantiated because they were abstract. I wrote (minimal) concrete implementations.

### CODE REVIEW

**Comment by davebshow** [comment]
Thanks @leifurhauks. Question: does a float value have to be a number? I can't do `float_prop = '1.14'`?

Also, what is the behavior when someone does something like:

``` python
v = MyVert()
v.bool_prop = 'hello'
v.bool_prop
# 'hello'? or True
```

**Comment by leifurhauks** [comment]
For your first example, my gut told me that users should convert a string explicitly with `float('1.14')`. If I accidentally assign some string that doesn't parse as a float, it would be good to see a validation error right away, rather an error that shows up when I try to send it to the database. I suppose that would also be accomplished by converting to float on validation / assignment.

For the second example, the main thing is that it's converted before being sent to the database, but I think I'd expect it to be `True`, not `'hello'`.

I'm not feeling adamant about these points; I needed to use `Float` and `Bool` this morning, so I just put together these implementations quickly.

Your questions make me think that it might make sense for input values to be run through `to_ogm` on assignment. What do you think?

**Comment by davebshow** [comment]
Well, upon assignment the `PropertyDescriptor` will call `validate`, so as is, whatever validate returns is the value for the prop. In my mind, `to_ogm` is more to deal with weird formats that may be returned by the db query. For example, the hack we used to store IPv6 on Titan with the old Goblin had to do some funky bitwise operation when converting to and from Python 3s IP objects.

**Comment by davebshow** [comment]
Also, I forgot to mention, because the descriptor calls `validate`, an error would be thrown upon assignment. If it were this:

``` python
    def validate(self, val):
        if val is not None:
            try:
                return float(val)
            except ValueError as e:
                raise exception.ValidationError(
                    '{} is not a valid float'.format(val)) from e
```

This would throw an error:

``` python
vertex.float_prop = 'hello'
# ValidationError gets raised
```

**Comment by leifurhauks** [comment]
Fair enough, that works for me.

**Comment by davebshow** [comment]
I was thinking, what should we do in the case where the db returns a value that wouldn't pass validation. For example, if a property that was declared as a integer in goblin that was changed to a string in the db. Should we just accept it, or should we raise another error, like `DatabaseValueError`?

**Comment by davebshow** [comment]
Well, we have conflicts now but I think this is done. Time to merge and transfer I think...

**Pull request merged**
